import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import router from './router';
import './assets/Globalstyle/fonts.css';
import "ol/ol.css";
import PrimeVue from "primevue/config";
import ConfirmationService from "primevue/confirmationservice";
import ToastService from "primevue/toastservice";
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount('#app');
